// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/DashboardStatTilesPreview.tsx": () => import("../components/mockups/DashboardStatTilesPreview.tsx"),
  "./components/mockups/DashboardStatsTilesV1.tsx": () => import("../components/mockups/DashboardStatsTilesV1.tsx"),
  "./components/mockups/StatTilesV2.tsx": () => import("../components/mockups/StatTilesV2.tsx")
};
